# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(help_text='描述', max_length=255, verbose_name='meta 描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(help_text='描述', max_length=255, verbose_name='meta 描述'),
        ),
    ]
